//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Varsayilan {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Varsayilan() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Varsayilan", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklaması.
        /// </summary>
        internal static string aciklamasi {
            get {
                return ResourceManager.GetString("aciklamasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adınız ve Soyadınız...
        /// </summary>
        internal static string adiniz_soyadiniz {
            get {
                return ResourceManager.GetString("adiniz_soyadiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADRES.
        /// </summary>
        internal static string adres {
            get {
                return ResourceManager.GetString("adres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.Alt Kategori.
        /// </summary>
        internal static string alt_kategori_1 {
            get {
                return ResourceManager.GetString("alt_kategori_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.Alt Kategori.
        /// </summary>
        internal static string alt_kategori_2 {
            get {
                return ResourceManager.GetString("alt_kategori_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.Alt Kategori.
        /// </summary>
        internal static string alt_kategori_3 {
            get {
                return ResourceManager.GetString("alt_kategori_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anasayfa.
        /// </summary>
        internal static string anasayfa {
            get {
                return ResourceManager.GetString("anasayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana Kategori.
        /// </summary>
        internal static string ana_kategori {
            get {
                return ResourceManager.GetString("ana_kategori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arama Alanını Doldurunuz...
        /// </summary>
        internal static string arama_alani_mesaj {
            get {
                return ResourceManager.GetString("arama_alani_mesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arama Kriterleri.
        /// </summary>
        internal static string arama_kriteri {
            get {
                return ResourceManager.GetString("arama_kriteri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aranacak Kelime.
        /// </summary>
        internal static string aranacak_kelime {
            get {
                return ResourceManager.GetString("aranacak_kelime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Özgeçmişiniz başarılı şekilde sisteme kaydedilmiştir...
        /// </summary>
        internal static string basarili_ozgecmis_mesaj {
            get {
                return ResourceManager.GetString("basarili_ozgecmis_mesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Özgeçmişiniz alınırken bir sorun oluştu. Lütfen tekrar Deneyiniz...
        /// </summary>
        internal static string basarisiz_ozgecmis_mesaj {
            get {
                return ResourceManager.GetString("basarisiz_ozgecmis_mesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BELGELERİMİZ.
        /// </summary>
        internal static string belgelerimiz {
            get {
                return ResourceManager.GetString("belgelerimiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bizden Haberler.
        /// </summary>
        internal static string bizden_haberler {
            get {
                return ResourceManager.GetString("bizden_haberler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bize Ulaşın.
        /// </summary>
        internal static string bize_ulasin {
            get {
                return ResourceManager.GetString("bize_ulasin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dosyanız...
        /// </summary>
        internal static string cv_dosyaniz {
            get {
                return ResourceManager.GetString("cv_dosyaniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Cv dosyanızı yükleyiniz..
        /// </summary>
        internal static string cv_hata_mesaj {
            get {
                return ResourceManager.GetString("cv_hata_mesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detay.
        /// </summary>
        internal static string detay {
            get {
                return ResourceManager.GetString("detay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detay.
        /// </summary>
        internal static string detayli_incele {
            get {
                return ResourceManager.GetString("detayli_incele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokümanlar (Pdf).
        /// </summary>
        internal static string dokumanlar_pdf {
            get {
                return ResourceManager.GetString("dokumanlar_pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DUYURULAR.
        /// </summary>
        internal static string duyurular {
            get {
                return ResourceManager.GetString("duyurular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genel E-katalog Görüntüle.
        /// </summary>
        internal static string e_katalog_goruntule {
            get {
                return ResourceManager.GetString("e_katalog_goruntule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-POSTA.
        /// </summary>
        internal static string e_posta {
            get {
                return ResourceManager.GetString("e_posta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-posta Adresiniz...
        /// </summary>
        internal static string e_posta_adres {
            get {
                return ResourceManager.GetString("e_posta_adres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fan E-katalog Görüntüle.
        /// </summary>
        internal static string fan_e_katalog_goruntule {
            get {
                return ResourceManager.GetString("fan_e_katalog_goruntule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönder.
        /// </summary>
        internal static string gonder {
            get {
                return ResourceManager.GetString("gonder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HABERLER.
        /// </summary>
        internal static string haberler {
            get {
                return ResourceManager.GetString("haberler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haberlerimiz.
        /// </summary>
        internal static string haberlerimiz {
            get {
                return ResourceManager.GetString("haberlerimiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haber Detay.
        /// </summary>
        internal static string haber_detay {
            get {
                return ResourceManager.GetString("haber_detay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haber Resimleri.
        /// </summary>
        internal static string haber_resimleri {
            get {
                return ResourceManager.GetString("haber_resimleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAKKIMIZDA.
        /// </summary>
        internal static string hakkimizda {
            get {
                return ResourceManager.GetString("hakkimizda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HARİTADA YERİMİZ.
        /// </summary>
        internal static string haritada_yerimiz {
            get {
                return ResourceManager.GetString("haritada_yerimiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İLETİŞİM.
        /// </summary>
        internal static string iletisim {
            get {
                return ResourceManager.GetString("iletisim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen kullanıcı adınızı yazınız..
        /// </summary>
        internal static string iletisim_ad_hata_mesaj {
            get {
                return ResourceManager.GetString("iletisim_ad_hata_mesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesajınız başarılı bir şekilde gönderilmiştir...
        /// </summary>
        internal static string iletisim_basarili {
            get {
                return ResourceManager.GetString("iletisim_basarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesajınız gönderilememiştir. Lütfen tekrar deneyiniz...
        /// </summary>
        internal static string iletisim_basarisiz {
            get {
                return ResourceManager.GetString("iletisim_basarisiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen geçerli bir mail adresi yazınız...
        /// </summary>
        internal static string iletisim_gecerli_mail_hata_mesaj {
            get {
                return ResourceManager.GetString("iletisim_gecerli_mail_hata_mesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen mail adresinizi yazınız..
        /// </summary>
        internal static string iletisim_mail_hata_mesaj {
            get {
                return ResourceManager.GetString("iletisim_mail_hata_mesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen mesajınızı Yazınız....
        /// </summary>
        internal static string iletisim_mesaj_hata_mesaj {
            get {
                return ResourceManager.GetString("iletisim_mesaj_hata_mesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen telefon numaranızı yazınız....
        /// </summary>
        internal static string iletisim_telefon_hata_mesaj {
            get {
                return ResourceManager.GetString("iletisim_telefon_hata_mesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İnsan Kaynakları.
        /// </summary>
        internal static string insan_kaynaklari {
            get {
                return ResourceManager.GetString("insan_kaynaklari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapat.
        /// </summary>
        internal static string kapat {
            get {
                return ResourceManager.GetString("kapat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katalog Ara.
        /// </summary>
        internal static string katalog_ara {
            get {
                return ResourceManager.GetString("katalog_ara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katalog Arama Sonuçları.
        /// </summary>
        internal static string katalog_arama_sonuc {
            get {
                return ResourceManager.GetString("katalog_arama_sonuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen kullanıcı adınızı yazınız..
        /// </summary>
        internal static string kullanici_ad_bosluk_hata {
            get {
                return ResourceManager.GetString("kullanici_ad_bosluk_hata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkımızda.
        /// </summary>
        internal static string kurumsal {
            get {
                return ResourceManager.GetString("kurumsal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listelenecek Ürün Kategorisi.
        /// </summary>
        internal static string list_urun_kategori {
            get {
                return ResourceManager.GetString("list_urun_kategori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARKALARIMIZ.
        /// </summary>
        internal static string markalarimiz {
            get {
                return ResourceManager.GetString("markalarimiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BİZDEN HABERLER.
        /// </summary>
        internal static string menu_bizden_haberler {
            get {
                return ResourceManager.GetString("menu_bizden_haberler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesajınız...
        /// </summary>
        internal static string mesajiniz {
            get {
                return ResourceManager.GetString("mesajiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MİSYONUMUZ.
        /// </summary>
        internal static string misyonumuz {
            get {
                return ResourceManager.GetString("misyonumuz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elektrik Motorları E-katalog Görüntüle.
        /// </summary>
        internal static string motor_e_katalog_goruntule {
            get {
                return ResourceManager.GetString("motor_e_katalog_goruntule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ölçüler - Teknik Katalog.
        /// </summary>
        internal static string olculer_teknik_katalog {
            get {
                return ResourceManager.GetString("olculer_teknik_katalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Özellikler.
        /// </summary>
        internal static string ozellikler {
            get {
                return ResourceManager.GetString("ozellikler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Özgeçmişinizi Gönderin.
        /// </summary>
        internal static string ozgecmis_gonder {
            get {
                return ResourceManager.GetString("ozgecmis_gonder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pdf Görüntüle.
        /// </summary>
        internal static string pdf_goruntulue {
            get {
                return ResourceManager.GetString("pdf_goruntulue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pdf İndir.
        /// </summary>
        internal static string pdf_indir {
            get {
                return ResourceManager.GetString("pdf_indir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pompa E-katalog Görüntüle.
        /// </summary>
        internal static string pompa_e_katalog_goruntule {
            get {
                return ResourceManager.GetString("pompa_e_katalog_goruntule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redüktör E-katalog Görüntüle.
        /// </summary>
        internal static string reduktor_e_katalog_goruntule {
            get {
                return ResourceManager.GetString("reduktor_e_katalog_goruntule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resimleri.
        /// </summary>
        internal static string resimleri {
            get {
                return ResourceManager.GetString("resimleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resim Galerisi.
        /// </summary>
        internal static string resim_galerisi {
            get {
                return ResourceManager.GetString("resim_galerisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son Haberler.
        /// </summary>
        internal static string son_haberler {
            get {
                return ResourceManager.GetString("son_haberler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TARİHÇEMİZ.
        /// </summary>
        internal static string tarihcemiz {
            get {
                return ResourceManager.GetString("tarihcemiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEKNİK KATALOGLAR.
        /// </summary>
        internal static string teknik_katalog {
            get {
                return ResourceManager.GetString("teknik_katalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefonunuz...
        /// </summary>
        internal static string telefon {
            get {
                return ResourceManager.GetString("telefon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tümü.
        /// </summary>
        internal static string tumu {
            get {
                return ResourceManager.GetString("tumu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm Duyurular.
        /// </summary>
        internal static string tum_duyurular {
            get {
                return ResourceManager.GetString("tum_duyurular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm Haberler.
        /// </summary>
        internal static string tum_haberler {
            get {
                return ResourceManager.GetString("tum_haberler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm Videoları Gör.
        /// </summary>
        internal static string tum_videolari_gor {
            get {
                return ResourceManager.GetString("tum_videolari_gor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÜRÜNLER.
        /// </summary>
        internal static string urunler {
            get {
                return ResourceManager.GetString("urunler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürünlerimiz.
        /// </summary>
        internal static string urunlerimiz {
            get {
                return ResourceManager.GetString("urunlerimiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bir ürün arayın...
        /// </summary>
        internal static string urun_ara {
            get {
                return ResourceManager.GetString("urun_ara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Arama Sonuçları.
        /// </summary>
        internal static string urun_arama_sonuc {
            get {
                return ResourceManager.GetString("urun_arama_sonuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Ara.
        /// </summary>
        internal static string urun_ara_btn {
            get {
                return ResourceManager.GetString("urun_ara_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yst-reduktor-urun-bulunamadi.png.
        /// </summary>
        internal static string urun_bulunamadi_resim {
            get {
                return ResourceManager.GetString("urun_bulunamadi_resim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Detay.
        /// </summary>
        internal static string urun_detay {
            get {
                return ResourceManager.GetString("urun_detay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün kataloğu için firmamızla iletişime geçiniz...
        /// </summary>
        internal static string urun_dokuman_yuklenmedi {
            get {
                return ResourceManager.GetString("urun_dokuman_yuklenmedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Katalogları.
        /// </summary>
        internal static string urun_katalog {
            get {
                return ResourceManager.GetString("urun_katalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÜRÜN KATEGORİLERİ.
        /// </summary>
        internal static string urun_kategorileri {
            get {
                return ResourceManager.GetString("urun_kategorileri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Kodu.
        /// </summary>
        internal static string urun_kodu {
            get {
                return ResourceManager.GetString("urun_kodu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Resimleri.
        /// </summary>
        internal static string urun_resimler {
            get {
                return ResourceManager.GetString("urun_resimler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu ürün için henüz resim yüklenmemiştir..
        /// </summary>
        internal static string urun_resim_yuklenmedi {
            get {
                return ResourceManager.GetString("urun_resim_yuklenmedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videolarımız.
        /// </summary>
        internal static string videolarimiz {
            get {
                return ResourceManager.GetString("videolarimiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VİZYONUMUZ.
        /// </summary>
        internal static string vizyonumuz {
            get {
                return ResourceManager.GetString("vizyonumuz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Yanlış Dosya Türü! Özgeçmişiniz için jpg,png,jpeg,doc,docx,pdf formatları geçerlidir.Lütfen bu tür dosyalar yükleyiniz.. .
        /// </summary>
        internal static string yanlis_dosya_mesaj {
            get {
                return ResourceManager.GetString("yanlis_dosya_mesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youtube Kanalımız.
        /// </summary>
        internal static string youtube_kanalimiz {
            get {
                return ResourceManager.GetString("youtube_kanalimiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y&lt;span&gt;S&lt;/span&gt;T Türkiye Ofis.
        /// </summary>
        internal static string yst_turk_ofis {
            get {
                return ResourceManager.GetString("yst_turk_ofis", resourceCulture);
            }
        }
    }
}
